### ISSUE TITLE
how to handle subscriptions

### ISSUE THREAD

**Issue by BernardA** [Luehang/react-paypal-button-v2#11]
Is it possible to handle subscriptions? If so, can you advise how.
Thanks

**Comment by orenkudev** [comment]
@BernardA  did you manage to address recurring payments?

**Comment by BernardA** [comment]
I did but without using your plugin. Subscriptions still use v1 ( in a very convoluted process ).
thanks

**Comment by orenkudev** [comment]
@BernardA Can you please direct me on how to handle it? Maybe I can enhance this package to support it (and give back to the community

**Comment by BernardA** [comment]
Here you have the docs: https://developer.paypal.com/docs/subscriptions/#how-a-subscriptions-integration-works.

Note that this is a completely different animal as related to the standard Smart Payment Button. There are a number of steps, some of which better be handled server side.
Basically:
- get an access token from Paypal ( shortlived) 
- create a product
- create a plan
- place a regular button in the appropriate page on the site where the client will initiate the subscription approval process, being redirected to Paypal.
- sent back to merchant site with approval/cancellation url

Also note that the response from Paypal may vary depending on how much client information the merchant site sent .
Being the case that this is v1, I assume that Paypal will also upgrade this to v2 in the near future. So, not sure it is worth putting the effort to set up a soon to be deprecated API.
