### ISSUE TITLE
Unable to import this dependency in windows environment

### ISSUE THREAD

**Issue by maxiaolin9495** [Luehang/react-paypal-button-v2#16]
Hello,

thank you to provide this dependency, for now i've meet sth unexpected when i try to import your project into my local dependencies. 

`npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
> react-paypal-button-v2@2.3.2 preinstall C:\Users\xiaolinma\Desktop\findmycook-frontend\Frontend\node_modules\react-paypal-button-v2
> rm -rf dist`

and this "rm -rf dist " could not be accepted by windows commandline, thus my install failed

**Comment by maxiaolin9495** [comment]
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paypal-button-v2@2.3.2 preinstall: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paypal-button-v2@2.3.2 preinstall script.`

this is the err info

**Comment by Luehang** [comment]
Hi,

This is a building environment error. A temporary fix is to input the command manually along with manually doing it yourself.

**Comment by Luehang** [comment]
Hi,

The Linux `rm` command has now been replaced with a cross-platform command.  Check out the new commits.
