### ISSUE TITLE
[BUG] 'rm' is not recognized as an internal or external command on Windows 10

### ISSUE THREAD

**Issue by patomation** [Luehang/react-paypal-button-v2#19]
**To Do First**
- [X] Did you try latest release?
- [X] Did you look for existing matching issues?

**Software Package Version:**
Latest Release

**Describe the bug**
When installing the npm package on a windows machine there is the following error:
```
> rm -rf dist

'rm' is not recognized as an internal or external command,
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paypal-button-v2@2.3.2 preinstall: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paypal-button-v2@2.3.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\patrick\AppData\Roaming\npm-cache\_logs\2019-08-06T11_38_56_956Z-debug.log
```

**To Reproduce**
1. Go to project on a windows machine
2. Run the following command:
``` npm install npm install react-paypal-button-v2```

**Expected behavior**
Expected the npm module to install without breaking or needing os specific commands...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - React Version: NA

**Additional context**
Thanks for looking at this bug. Have a good day.

**Comment by Luehang** [comment]
Hi,

The Linux `rm` command has now been replaced with a cross-platform command.  Check out the new commits.
