### ISSUE TITLE
[FEATURE REQUEST]Add a disableShipping prop

### ISSUE THREAD

**Issue by CloudPower97** [Luehang/react-paypal-button-v2#21]
I think it would be easier to add a `disableShipping` `prop` than manually disable it as in #9 

The proposed solution is to add 
```javascript
  application_context: {
    shipping_preference: 'NO_SHIPPING',
   }
```
manually when `disableShipping` `prop` is provided.

Let me know if you are okay with this, @Luehang , so I can open a __P.R__ :)

**Comment by Luehang** [comment]
Thanks for the pull request.  It has been merged.
