### ISSUE TITLE
[QUESTION] multiple paypal buttons on 1 page

### ISSUE THREAD

**Issue by slk333** [Luehang/react-paypal-button-v2#22]
**To Do First**
- [x] Take a look in the [README](https://github.com/Luehang/react-paypal-button-v2/blob/master/README.md)
- [x] Take a look in the [docs](https://luehangs.site/lue_hang/projects/react-paypal-button-v2)

**Ask your Question**
Is it possible to have multiple`<PayPalButton> ` on 1 page? From what I experience, only 1 will appear

**Comment by davidwieler** [comment]
Would like to know the answer to this as well.
Seems to be that for multiple buttons to appear on the page at the same time, a unique ID is required on each, but there is no way to do that currently.

**Comment by Luehang** [comment]
Hi guys,

Having multiple buttons on a single page will work.  Already been done.  You guys should give it a go and try it for yourself.

**Comment by slk333** [comment]
Just to be clear I tried it yesterday and it doesn't work, for the reason explained by @davidwieler

**Comment by Luehang** [comment]
Hi,

When I tried it, it works.  Can you give me more details?

**Comment by slk333** [comment]
For me it **only works** with the hot reloading.
Once you **reload manually the page**, only one will appear.

**Comment by YassienW** [comment]
You can't have multiple buttons with different settings.

I'm facing a situation where my SPA website needs a button for a subscription and a button for an order, it doesn't seem to be possible so far.

**Comment by sebdum** [comment]
> You can't have multiple buttons with different settings.
> 
> I'm facing a situation where my SPA website needs a button for a subscription and a button for an order, it doesn't seem to be possible so far.

Yup, this is still not possible easily. Two subscriptions or multiple orders are fine, but mixing the two gives following error: 

`Uncaught Error: Do not pass both createSubscription and createOrder`
