### ISSUE TITLE
[BUG] Rimraf Dependency Breaks Some Machines

### ISSUE THREAD

**Issue by berkona** [Luehang/react-paypal-button-v2#27]
Ran into using CodeBuild's NodeJS 10.x Images.  May PR a fix tonight if I have time.

**To Do First**
- [x] Did you try latest release?
- [x] Did you look for existing matching issues?

**Software Package Version: 2.4.1**

**Describe the bug**
Use of "rimraf" in 2.4.1 accidently creates global dependency for "rimraf".

If "rimraf" is not installed on machine, npm install/rebuild commands will fail with message like:
```
> react-paypal-button-v2@2.4.1 preinstall /home/jon/src/rsm/robinsnestdesigns.com/node_modules/react-paypal-button-v2
> rimraf dist

sh: rimraf: command not found
```

**To Reproduce**
1. `sudo npm uninstall -g rimraf`
2. `cd <project which has dep of react-paypal-button-v2@2.4.1>`
3. `rm -rf node_modules/ && rm -f package-lock.json`
4. `npm install`
5. **Install fails**
6. `sudo npm install -g rimraf`
7. `npm install`
8. **Install succeeds**

**Expected behavior**
rimraf calls should use `node node_modules/rimraf/bin.js` to ensure package is using proper rimraf package and not global installed version

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser: N/A
 - React Version: N/A

**Comment by 9jaboy** [comment]
@Luehang This happens on Azure piples

**Comment by sephiroth56** [comment]
on Heroku happens too

**Comment by Kuldevsingh** [comment]
Hi, I got the same error but after installing npm using npm install, it resolved my problems

**Comment by 9jaboy** [comment]
@Luehang when will you fix this?

**Comment by valleywood** [comment]
Still a problem :(

**Comment by Luehang** [comment]
Hi,

Install latest to solve that error.  Thanks.

## :large_blue_diamond: Install

```sh
$ npm install react-paypal-button-v2@2.6.1 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.6.1
```
