### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CodingOni** [Luehang/react-paypal-button-v2#29]
**To Do First**
- [ yes] Did you try latest release?
- [yes ] Did you look for existing matching issues?

**Software Package Version:**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - React Version: [e.g. 22]

**Additional context**

**Comment by Luehang** [comment]
Hi,

Can you fill out the entire form or re-open this issue?  Thanks.
