### ISSUE TITLE
[BUG] not exported types

### ISSUE THREAD

**Issue by bombek92** [Luehang/react-paypal-button-v2#35]
**To Do First**
- [x] Did you try latest release?
- [x] Did you look for existing matching issues?

**Software Package Version:** 2.4.1

Excuse me, for removing the issue schema, but I noticed that even tough you do use typescript, the types aren't properly builded/exported into npm.

Can you fix it?

**Comment by esemeniuc** [comment]
I'm running into the same issue, please export the types on `2.6.1`

**Comment by LeafHacker** [comment]
The package.json indicates the types should be at `dist/index.d.ts` however they don't appear to have been exported.
![image](https://user-images.githubusercontent.com/23565638/74105564-f5b87a80-4b56-11ea-8b77-6fe1d4188c80.png)

**Comment by devuxer** [comment]
@Jonasfranz,

Do you have a quick workaround to allow us to use this in a TypeScript project until the pull request is available? Thx!

**Comment by jonasfranz** [comment]
@devuxer You can use the master branch of my repository in your project. Simply replace the version number in your package.json file with: `github:jonasfranz/react-paypal-button-v2#master`

**Comment by devuxer** [comment]
@jonasfranz, Ahh, so that's how you do it. I ended up just cloning the original project then manually applying the changes in your pull request (which wasn't bad since only a couple files). I hadn't thought of cloning from yours, though. Will do that next time. TIL! Thanks for your help 😎
