### ISSUE TITLE
'rm' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by manimurugank** [Luehang/react-paypal-button-v2#5]
![image](https://user-images.githubusercontent.com/15648637/54427977-09d6da80-4742-11e9-93ad-33d5fd469a05.png)

'rm' is not recognized as an internal or external command,

[4/4] Building fresh packages...
[1/3] ⠂ node-sass
[2/3] ⠂ styled-components
error e:\projects\GVS%20System%20Rebuild\src\GVS.VoucherSales\UI\gvs-vouchersales-public-app\node_modules\react-paypal-button-v2: Command failed.
Exit code: 1
Command: rm -rf dist
Arguments:
Directory: e:\projects\GVS%20System%20Rebuild\src\GVS.VoucherSales\UI\gvs-vouchersales-public-app\node_modules\react-paypal-button-v2
Output:
'rm' is not recognized as an internal or external command,

**Comment by Luehang** [comment]
Hi,

You are on **Windows** and those commands are only for **Mac OS** or bash.

**Comment by juiceJosh** [comment]
So installing this component is not doable on Windows due to that limitation? @Luehang

**Comment by Luehang** [comment]
Hi,

The Linux `rm` command has now been replaced with a cross-platform command.  Check out the new commits.

**Comment by 9jaboy** [comment]
@Luehang which version is this fix in?

**Comment by Luehang** [comment]
Hi,

Install `2.4.1` to solve that platform error.  Thanks.

## :large_blue_diamond: Install

```sh
$ npm install react-paypal-button-v2@2.4.1 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.4.1
```
