### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by carljustineoyales** [Luehang/react-paypal-button-v2#53]
**To Do First**
- [x] Take a look in the [README](https://github.com/Luehang/react-paypal-button-v2/blob/master/README.md)
- [x] Take a look in the [docs](https://luehangs.site/lue_hang/projects/react-paypal-button-v2)

**Ask your Question**

I'm getting a 404 error when calling my server to save the transaction onSuccess even using get requests. How to fix this issue?
**Tags**

**Comment by Luehang** [comment]
Hi,

This is a back end issue.  Make sure you have the right path and make sure it is a valid and open path to your server.
