### ISSUE TITLE
How to hide Debit or Credit Card button

### ISSUE THREAD

**Issue by sumitmoga** [Luehang/react-paypal-button-v2#58]
![image](https://user-images.githubusercontent.com/49942821/78821150-ac6d9580-79f6-11ea-88bf-bf8983d38ac6.png)
I want to hide above debit or credit card button ...but didn't found anything for this.

**Comment by xcademy-dev** [comment]
hey! 
```
<PayPalButton 
           options={{ 
              disableFunding:'credit,card'
          }}
</PayPalButton>
```

**Comment by sumitmoga** [comment]
> hey!
> 
> ```
> <PayPalButton 
>            options={{ 
>               disableFunding:'credit,card'
>           }}
> </PayPalButton>
> ```

Thanks @xcademy-dev  its working now
