### ISSUE TITLE
remove the Polyfill

### ISSUE THREAD

**Issue by abumalick** [Luehang/react-paypal-button-v2#6]
Thank you for the component, the code looks very clean 👍 

I was surprised to see that you import babel polyfill in the component. The polyfills are generally added in the beginning of an app, it is not included in the components.

Usually if a library needs a polyfill, it will be mentioned in the Readme/documentation. A good example of this is React:
https://reactjs.org/docs/javascript-environment-requirements.html

What do you think ?

**Comment by abumalick** [comment]
@Luehang ?

**Comment by Gr8z** [comment]
I get this error message:

```
`@babel/polyfill` is deprecated. Please, use required parts of `core-js`
[1]   and `regenerator-runtime/runtime` separately
```

**Comment by Luehang** [comment]
Hi,

`@babel/polyfill` has been removed as a dependency.  Thanks.

## :large_blue_diamond: Install

```sh
$ npm install react-paypal-button-v2@2.4.1 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.4.1
```
