### ISSUE TITLE
Wrong button behavior

### ISSUE THREAD

**Issue by blanknamed** [Luehang/react-paypal-button-v2#7]
When you press on checkout button with chrome dev console opened button do not work or if onSuccess method was set proceed to execution of it.

Spotted on demo from repository
Chrome 73.0.3683.103

**Comment by Luehang** [comment]
Hi,

`onSuccess` is only triggered on the successful approval of the transaction sent back from PayPal's api or it would have thrown an error.  Have you check for any errors thrown?
