### ISSUE TITLE
[FEATURE REQUEST] add discount to options

### ISSUE THREAD

**Issue by InvaderSquibs** [Luehang/react-paypal-button-v2#74]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a coupon code for paypal and have not seen a clear way to add a discount to the button.

**Describe the solution you'd like**
If possible I would appreciate allowing an option to add a discount to the button. 

**Describe alternatives you've considered**
The alternative that I am currently using, is having two separate paypal plan ids. One is the full price the other is the discounted price. So if the coupon code matches then I just use the plan id for the discount. I would to be able to have just the one plan id for pay pal.

**Additional context**
Thank you so much for making something decent from the mess that paypal had provided. It helps out so much!

**Comment by balmacefa** [comment]
Paypal doesn't not provide a discount system for subscription, you have to build your own or use brain Tree

**Comment by InvaderSquibs** [comment]
Lol of course. Oh man I don't envy you for doing all that code to make everything that much easier. Pay pal is it's own beast thanks for the context. much appreciated.
