### ISSUE TITLE
[QUESTION] Javascript Errors

### ISSUE THREAD

**Issue by Gus19** [Luehang/react-paypal-button-v2#85]
Hello,

I'm starting my paypal integration and I have js errors and I don't understand where they are coming from?

![image](https://user-images.githubusercontent.com/6604549/93586898-4fb0d680-f9a9-11ea-8554-333e0faeabdf.png)

There is my Button : 
```
<PayPalButton
      amount="2"
      shippingPreference="NO_SHIPPING"
      onSuccess={(details, data) => {
        console.log("Transaction completed", details, data);
      }}
      style={{
        shape: 'rect',
        color: 'blue',
        layout: 'horizontal',
        label: 'pay',
        tagline: false
      }}
      options={{
        clientId: "XX",
        currency: "EUR"
      }}
    />
```

Thanks for your help !

**Comment by frasergr** [comment]
@Gus19 For me, it was due to having Brave shield and uBlock Origins enabled in the localhost environment. After disabling both of those the errors were gone.

**Comment by Gus19** [comment]
Oh, good to know. Thanks !
