### ISSUE TITLE
Disable shipping

### ISSUE THREAD

**Issue by dicristomanuel** [Luehang/react-paypal-button-v2#9]
I can't seem to be able to disable shipping for the order when checking out with a credit card. The items I'm selling are not going to be shipped and the field confuses the users. I've been looking into the documentation and tried to add the `NOSHIPPING` option and it still shows up.

Any ideas?

<img width="447" alt="Screen Shot 2019-05-09 at 11 21 56 AM" src="https://user-images.githubusercontent.com/11862464/57477045-b1592080-724c-11e9-91a7-427ea16b0d5d.png">

**Comment by dicristomanuel** [comment]
I just answered my own question :)
In case anyone runs into the same use case, this is the implementation:

```jsx
<PayPalButton
  createOrder={(data, actions) => actions.order.create({
  purchase_units: [{
    amount: {
      currency_code: 'USD',
      value: '1.99',
     },
   }],
  application_context: {
    shipping_preference: 'NO_SHIPPING',
   },
  })}
  onApprove={(_data, actions) => { 
    ...
  }}                
/>
```

**Comment by Luehang** [comment]
## :large_blue_diamond: Another Usage Alternative

### :small_blue_diamond: Install

Type in the following to the command line to install the dependency. 

```sh
$ npm install react-paypal-button-v2@2.5.0 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.5.0
```

<br/>

### :small_blue_diamond: Implement

```javascript
import { PayPalButton } from "react-paypal-button-v2";

export default class Example Component {
  render() {
    return (
      <PayPalButton
        amount="0.01"
        shippingPreference="NO_SHIPPING" // default is "GET_FROM_FILE"
        onSuccess={(details, data) => {
          alert("Transaction completed by " + details.payer.name.given_name);

          // OPTIONAL: Call your server to save the transaction
          return fetch("/paypal-transaction-complete", {
            method: "post",
            body: JSON.stringify({
              orderID: data.orderID
            })
          });
        }}
      />
    );
  }
}
```
